function cardString = outputCard(cardVal)


conversionCard = {'2',1;...
    '3',2;...
    '4',3;...
    '5',4;...
    '6',5;...
    '7',6;...
    '8',7;...
    '9',8;...
    '10',9;...
    'j',10;...
    'q',11;...;
    'k',12;...;
    'a',13};

% Spade 1
% Club 2
% Diamond 3
% Heart 4


conversionSuit = {'S',1;...
    'C',2;...
    'D',3;...
    'H',4;};


card = cardVal(1); 
suit = cardVal(2); 

card = conversionCard{cell2mat(conversionCard(:,2)) == card,1}; 
suit = conversionSuit{cell2mat(conversionSuit(:,2)) == suit,1}; 

cardString = [card suit];

end